### PR TITLE
getting curl's library not system one, fix #173

### LINKED ISSUE #173: cmake imported target might be broken
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have the impression that the latest libnetcdf package on conda-forge causes problems when using libnetcdf as a cmake imported target. The cmake imported target somehow causes the fimex build to expect libz.so in the fimex build directory, and libz.so is obviously not there:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=676229&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0

(See line 499 in the build output.) This problem has not been present in previous libnetcdf versions, and is not present when using libnetcdf via pkg-config instead of as a cmake imported target.

### Installed packages

```shell
conda build
```

### Environment info

```shell
conda version : 23.1.0
    conda-build version : 3.24.0
         python version : 3.8.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.8.16 Linux/4.15.0-206-generic ubuntu/18.04.6 glibc/2.27
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

File: recipe/build.sh [hunk 1]
```diff
@@ -1,7 +1,17 @@
...
+    LD_SUFFIX="dylib"
+else
+    LD_SUFFIX="DLL"
+fi
+
 
 # Build static.
 cmake -D CMAKE_INSTALL_PREFIX=$PREFIX \
+      -D CURL_INCLUDE_DIR=$PREFIX/include \
+      -D CURL_LIBRARY=$PREFIX/lib/libcurl.$LD_SUFFIX \
```
Comment (ocefpaf) [inline recipe/build.sh]: Please see https://github.com/conda-forge/libnetcdf-feedstock/pull/26/commits/3a84292a00b3d63167401eb7b5a01c28f4da9a29 for the use of `SHLIB_EXT`.

PS: the CIs indicate that it works and only conda-forge's curl is used :tada:

File: recipe/build.sh [hunk 2]
```diff
@@ -1,7 +1,17 @@
 #!/bin/bash
+if [ `uname` == "Linux" ]; then
+    LD_SUFFIX="so"
```
Comment (ocefpaf) [inline recipe/build.sh]: No need for the if-else clause. See my comment below.

File: recipe/build.sh [hunk 3]
```diff
@@ -1,7 +1,17 @@
...
+elif [ `uname` == "Darwin" ]; then
+    LD_SUFFIX="dylib"
+else
+    LD_SUFFIX="DLL"
```
Comment (ocefpaf) [inline recipe/build.sh]: Assuming that everything else is Windows can be dangerous for other people than conda-forge that use this recipe to build on various platforms.

**Comment by ocefpaf** [comment]
Travis-CI passed on my instance. Merging this to unlock #26 

Thanks @doutriaux1!
